/**
 * Security & Sanitization Utilities for estud.ai
 * Protects against XSS, injection, unhandled error leaks, and malicious payloads.
 */

// HTML entity map for escaping user-generated strings (standard OWASP body escapes)
const HTML_ESCAPES: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#x27;',
};

/**
 * Escapes potentially dangerous characters in user input to prevent XSS.
 */
export function sanitizeString(input: unknown): string {
  if (typeof input !== 'string') {
    return String(input ?? '');
  }
  return input.replace(/[&<>"']/g, (match) => HTML_ESCAPES[match] || match);
}

/**
 * Recursively sanitizes strings in an object or array.
 * Useful for validating raw imported JSON or user feedback payloads.
 */
export function sanitizeObject<T>(value: T): T {
  if (typeof value === 'string') {
    return sanitizeString(value) as unknown as T;
  }
  if (Array.isArray(value)) {
    return value.map((item) => sanitizeObject(item)) as unknown as T;
  }
  if (value !== null && typeof value === 'object') {
    const sanitizedObj: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(value)) {
      // Sanitize both key and value
      const cleanKey = sanitizeString(key);
      sanitizedObj[cleanKey] = sanitizeObject(val);
    }
    return sanitizedObj as T;
  }
  return value;
}

/**
 * Safe JSON parser that never throws and returns fallback on failure.
 */
export function safeJsonParse<T>(raw: string | null, fallback: T): T {
  if (!raw || typeof raw !== 'string') return fallback;
  try {
    const parsed = JSON.parse(raw);
    return parsed !== null && parsed !== undefined ? parsed : fallback;
  } catch {
    return fallback;
  }
}

/**
 * Light RFC-compliant email validation.
 */
export function isValidEmail(email: string): boolean {
  if (!email || typeof email !== 'string') return false;
  const re = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
  return re.test(email.trim());
}

/**
 * Format errors safely so internal details, tokens, or stack traces are not exposed to users.
 */
export function formatSafeError(err: unknown, fallbackMessage = 'Ocorreu um erro inesperado.'): string {
  if (!err) return fallbackMessage;
  if (typeof err === 'string') {
    // Strip file paths or technical identifiers
    return sanitizeString(err.replace(/([A-Z]:\\[^\s]+|\/[a-zA-Z0-9._-]+)+/g, '[caminho oculto]'));
  }
  if (err instanceof Error) {
    const msg = err.message || fallbackMessage;
    return sanitizeString(msg.replace(/([A-Z]:\\[^\s]+|\/[a-zA-Z0-9._-]+)+/g, '[caminho oculto]'));
  }
  return fallbackMessage;
}

/**
 * Robustly extracts and parses JSON generated by LLMs (ChatGPT, Claude, Gemini, DeepSeek).
 * Handles:
 * - Conversational text before/after codeblock
 * - ```json ... ``` or ``` ... ``` markdown formatting
 * - Single-line // and multi-line comments
 * - Trailing commas before } and ]
 */
export function extractAndParseJson<T = any>(rawText: string): { success: boolean; data?: T; error?: string } {
  if (!rawText || typeof rawText !== 'string') {
    return { success: false, error: 'Nenhum texto fornecido.' };
  }

  let text = rawText.trim();
  if (!text) {
    return { success: false, error: 'O texto fornecido está vazio.' };
  }

  // 1. If markdown codeblock is present (```json ... ``` or ``` ... ```), extract its inner content
  const codeBlockMatch = text.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
  if (codeBlockMatch && codeBlockMatch[1]) {
    text = codeBlockMatch[1].trim();
  } else {
    // 2. Look for outer JSON object or array bounds { ... } or [ ... ]
    const firstBrace = text.indexOf('{');
    const firstBracket = text.indexOf('[');
    let startIdx = -1;
    let isArray = false;

    if (firstBrace !== -1 && (firstBracket === -1 || firstBrace < firstBracket)) {
      startIdx = firstBrace;
    } else if (firstBracket !== -1) {
      startIdx = firstBracket;
      isArray = true;
    }

    if (startIdx !== -1) {
      const endChar = isArray ? ']' : '}';
      const lastIdx = text.lastIndexOf(endChar);
      if (lastIdx > startIdx) {
        text = text.substring(startIdx, lastIdx + 1);
      }
    }
  }

  // 3. Remove single-line comments (// ...) while preserving URLs like https://
  text = text.replace(/(^|[^:])\/\/[^\r\n]*/g, '$1');

  // 4. Remove multi-line comments (/* ... */)
  text = text.replace(/\/\*[\s\S]*?\*\//g, '');

  // 5. Remove trailing commas before closing braces/brackets (, } or , ])
  text = text.replace(/,(\s*[}\]])/g, '$1');

  try {
    const data = JSON.parse(text);
    return { success: true, data };
  } catch (err: any) {
    return {
      success: false,
      error: `JSON Inválido: ${err?.message || 'Verifique a formatação do texto gerado pela IA.'}`,
    };
  }
}
